*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 24.11.2021 at 23:10:45
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZMJE_UPL_CTRL_V.................................*
FORM GET_DATA_ZMJE_UPL_CTRL_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMJE_UPL_CTRL WHERE
(VIM_WHERETAB) .
    CLEAR ZMJE_UPL_CTRL_V .
ZMJE_UPL_CTRL_V-IOBJNM =
ZMJE_UPL_CTRL-IOBJNM .
ZMJE_UPL_CTRL_V-FIELD_NAME =
ZMJE_UPL_CTRL-FIELD_NAME .
ZMJE_UPL_CTRL_V-MANDATORY_MASK =
ZMJE_UPL_CTRL-MANDATORY_MASK .
ZMJE_UPL_CTRL_V-MD_CHECK =
ZMJE_UPL_CTRL-MD_CHECK .
ZMJE_UPL_CTRL_V-AD_HOC_CHECK =
ZMJE_UPL_CTRL-AD_HOC_CHECK .
    SELECT SINGLE * FROM RSDIOBJT WHERE
LANGU = 'E' AND
IOBJNM = ZMJE_UPL_CTRL-IOBJNM AND
OBJVERS = 'A' .
    IF SY-SUBRC EQ 0.
ZMJE_UPL_CTRL_V-TXTSH =
RSDIOBJT-TXTSH .
    ENDIF.
<VIM_TOTAL_STRUC> = ZMJE_UPL_CTRL_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMJE_UPL_CTRL_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMJE_UPL_CTRL_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMJE_UPL_CTRL_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMJE_UPL_CTRL WHERE
  IOBJNM = ZMJE_UPL_CTRL_V-IOBJNM AND
  FIELD_NAME = ZMJE_UPL_CTRL_V-FIELD_NAME .
    IF SY-SUBRC = 0.
    DELETE ZMJE_UPL_CTRL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMJE_UPL_CTRL WHERE
  IOBJNM = ZMJE_UPL_CTRL_V-IOBJNM AND
  FIELD_NAME = ZMJE_UPL_CTRL_V-FIELD_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMJE_UPL_CTRL.
    ENDIF.
ZMJE_UPL_CTRL-IOBJNM =
ZMJE_UPL_CTRL_V-IOBJNM .
ZMJE_UPL_CTRL-FIELD_NAME =
ZMJE_UPL_CTRL_V-FIELD_NAME .
ZMJE_UPL_CTRL-MANDATORY_MASK =
ZMJE_UPL_CTRL_V-MANDATORY_MASK .
ZMJE_UPL_CTRL-MD_CHECK =
ZMJE_UPL_CTRL_V-MD_CHECK .
ZMJE_UPL_CTRL-AD_HOC_CHECK =
ZMJE_UPL_CTRL_V-AD_HOC_CHECK .
    IF SY-SUBRC = 0.
    UPDATE ZMJE_UPL_CTRL ##WARN_OK.
    ELSE.
    INSERT ZMJE_UPL_CTRL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMJE_UPL_CTRL_V-UPD_FLAG,
STATUS_ZMJE_UPL_CTRL_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMJE_UPL_CTRL_V.
  SELECT SINGLE * FROM ZMJE_UPL_CTRL WHERE
IOBJNM = ZMJE_UPL_CTRL_V-IOBJNM AND
FIELD_NAME = ZMJE_UPL_CTRL_V-FIELD_NAME .
ZMJE_UPL_CTRL_V-IOBJNM =
ZMJE_UPL_CTRL-IOBJNM .
ZMJE_UPL_CTRL_V-FIELD_NAME =
ZMJE_UPL_CTRL-FIELD_NAME .
ZMJE_UPL_CTRL_V-MANDATORY_MASK =
ZMJE_UPL_CTRL-MANDATORY_MASK .
ZMJE_UPL_CTRL_V-MD_CHECK =
ZMJE_UPL_CTRL-MD_CHECK .
ZMJE_UPL_CTRL_V-AD_HOC_CHECK =
ZMJE_UPL_CTRL-AD_HOC_CHECK .
    SELECT SINGLE * FROM RSDIOBJT WHERE
LANGU = 'E' AND
IOBJNM = ZMJE_UPL_CTRL-IOBJNM AND
OBJVERS = 'A' .
    IF SY-SUBRC EQ 0.
ZMJE_UPL_CTRL_V-TXTSH =
RSDIOBJT-TXTSH .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMJE_UPL_CTRL_V-TXTSH .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMJE_UPL_CTRL_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMJE_UPL_CTRL_V-IOBJNM TO
ZMJE_UPL_CTRL-IOBJNM .
MOVE ZMJE_UPL_CTRL_V-FIELD_NAME TO
ZMJE_UPL_CTRL-FIELD_NAME .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMJE_UPL_CTRL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMJE_UPL_CTRL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMJE_UPL_CTRL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMJE_UPL_CTRL_V USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZMJE_UPL_CTRL-IOBJNM =
ZMJE_UPL_CTRL_V-IOBJNM .
ZMJE_UPL_CTRL-FIELD_NAME =
ZMJE_UPL_CTRL_V-FIELD_NAME .
ZMJE_UPL_CTRL-MANDATORY_MASK =
ZMJE_UPL_CTRL_V-MANDATORY_MASK .
ZMJE_UPL_CTRL-MD_CHECK =
ZMJE_UPL_CTRL_V-MD_CHECK .
ZMJE_UPL_CTRL-AD_HOC_CHECK =
ZMJE_UPL_CTRL_V-AD_HOC_CHECK .
    SELECT SINGLE * FROM RSDIOBJT WHERE
LANGU = 'E' AND
IOBJNM = ZMJE_UPL_CTRL-IOBJNM AND
OBJVERS = 'A' .
    IF SY-SUBRC EQ 0.
ZMJE_UPL_CTRL_V-TXTSH =
RSDIOBJT-TXTSH .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMJE_UPL_CTRL_V-TXTSH .
    ENDIF.
ENDFORM.
